<#include "./func.ftl">
<!-- Generated by ${author} on ${now?string("yyyy-MM-dd HH:mm:ss")} -->
<div class="box" id="app">
	<div class="box-header with-border">
		<h3 class="box-title">${table.remarks}详情</h3>
	</div>
	<div class="box-body">
		<div class="form-horizontal">
<#list table.columns as column>
	<#if column.displays?? && column.displays?size gt 0>
		<#list column.displays?keys as key>
			<#if key=='detail'>
				<#assign display=column.displays[key]>
			<div class="from-group">	
				<label class="col-xs-2 control-label"><#if column.remarks?? && column.remarks!="">${column.remarks}<#else>${column_name}</#if></label>
				<div class="col-xs-10">
					<p class="form-control-static">
						{{ item.${lower_underscore(column.name)}<#if column.dictionary??> | ${upper_camel(table.name)}.${lower_camel(column.name)}Filter</#if> }}
					</p>
				</div>
			</div>
			</#if>
		</#list>
	</#if>
</#list>
		</div>
	</div>
	<div class="box-footer text-center">
		<button @click.prevent="edit(item.id)" class="btn btn-default">修改</button>
		<button @click.prevent="remove(item.id)" class="btn btn-default">删除</button>
		<button @click.prevent="back" type="button" class="btn btn-default">返回</button>
	</div>
</div>
<script>
app = new Vue({
	el: '#app',
	data: {
		item: {}
	},
	filters:{
/*
<#assign flag=false>
<#list table.columns as column>
	<#if column.dictionary??>
		<#if flag>,</#if>
		${lower_camel(column.name)}Filter: function(i){
			return {
			<#list column.dictionary as key, value>
				${key}: "${value}"<#sep>,</#sep>
			</#list>
			}[i];
		}
		<#assign flag=true>
	</#if>
</#list>
*/
	},
	methods: {
		load: function(){
			let id = router.params.id;
			if(id){
				this.$http.get('./data/${lower_underscore(table.name)}/'+id).then(response => {
					let data = response.data;
					console.log('loaded.', data);
					this.$set(this, 'item', data.${lower_underscore(table.name)});
				});
			}
		},
		edit: function(id){
			router.goto('#${lower_underscore(table.name)}_form.html?id='+id);
		},
		remove: function(id){
			if(id && window.confirm('确定要删除"'+this.item.title+'"?')){
				this.$http.delete('./${lower_underscore(table.name)}/'+id, { body: {id: id}}).then(response => {
					this.$delete(this.$data.item, 'id');
					console.log('removed.');
					router.redirect('#${lower_underscore(table.name)}_list.html');
				});
			}
		},
		back: function(){
			router.history.back();
		}
	}
});
app.load();
</script>