<#include "./func.ftl">
<!-- Generated by ${author} on ${now?string("yyyy-MM-dd HH:mm:ss")} -->
<!-- form begin -->
<form method="POST">
<div class="box" id="app">
	<div class="box-header with-border">
		<h3 class="box-title">${table.remarks}信息</h3>
	</div>
	<div class="box-body">
<#list table.columns as column>
	<#if column.displays?? && column.displays?size gt 0>
		<#list column.displays?keys as key>
			<#if key=='form'>
				<#assign display=column.displays[key]>
				<#if display.element??>
					<#if display.element.class.simpleName=='Hidden'>
		<input id="${lower_camel(column.name)}" type="hidden" v-model="item.${lower_underscore(column.name)}" name="${lower_underscore(column.name)}"/>
					<#else>
		<div class="form-group">		
			<label for="${lower_camel('obj_'+column.name)}">
				<#if column.remarks?? && column.remarks!="">${column.remarks}<#else>${column_name}</#if><#if !column.nullable>*</#if>				
			</label>				
						<#switch display.element.class.simpleName>
							<#case 'Select'>
			<select id="${lower_camel('obj_'+column.name)}" v-model="item.${lower_underscore(column.name)}" name="${lower_underscore(column.name)}" class="form-control select2">
					<#if column.dictionary??>
						<#list column.dictionary as key, value>
				<option value="${key}">${value}</option>
						</#list>
					<#else>
				<option value="0">-</option>
					</#if>
			</select>
								<#break>
							<#case 'DatePicker'>
			<div class="input-group date">
				<div class="input-group-addon">
					<i class="fa fa-calendar"></i>
				</div>
				<input id="${lower_camel('obj_'+column.name)}" type="text" name="${lower_underscore(column.name)}" v-model="item.${lower_underscore(column.name)}" data-provide="datepicker" data-date-format="yyyy-mm-dd" class="form-control pull-right datepicker">
			</div>
								<#break>
							<#case 'DateMask'>
			<div class="input-group">
				<div class="input-group-addon">
					<i class="fa fa-calendar"></i>
				</div>
				<input id="${lower_camel('obj_'+column.name)}" type="text" name="${lower_underscore(column.name)}" v-model="item.${lower_underscore(column.name)}" class="form-control"/>
			</div>
								<#break>
							<#default>
			<input id="${lower_camel('obj_'+column.name)}" type="<#if is_number(column.type)>number<#else>text</#if>" name="${lower_underscore(column.name)}" v-model="item.${lower_underscore(column.name)}" placeholder="" value="" class="form-control"<#if !column.nullable> required</#if>/>
						</#switch>
		</div>						
					</#if>
				</#if>
			</#if>
		</#list>
	</#if>
</#list>
	</div>
	<div class="box-footer text-center">
		<button @click.prevent="save" type="button" class="btn btn-default">提交</button>
		<button @click.prevent="back" type="button" class="btn btn-default">返回</button>
	</div>
</form>
<!-- form end -->
</div>
<script>
app = new Vue({
	el: '#app',
	data: {
		item: {
	<#assign flag=true>
	<#list table.columns as column>
		<#if !column.primaryKey && column.defaultValue??>
			<#if !flag>, </#if>${lower_underscore(column.name)}: "${column.defaultValue}"
			<#assign flag=false>
		</#if>
	</#list>
		}
	},
	methods: {
		load: function(){
			let id = router.params.id;
			if(id){
				this.$http.get('./data/${lower_underscore(table.name)}/'+id).then(response => {
					let data = response.data;
					console.log('loaded.', data);
					this.$set(this, 'item', data.${lower_underscore(table.name)});
				});
			}
		},
		save: function(e){
			let id = this.item.id;
			if(!id){
				this.$http.post('./data/${lower_underscore(table.name)}', this.item).then(response => {
					console.log('saved.');
					router.redirect('#${lower_underscore(table.name)}_list.html');
				});
			}
			else{
				this.$http.put('./data/${lower_underscore(table.name)}/'+id, this.item).then(response => {
					console.log('updated.');
					router.redirect('#${lower_underscore(table.name)}_list.html');
				});			
			}
		},
		back: function(){
			router.history.back();
		}
	},
	mounted: function(){
		let self = this;
<#list table.columns as column>
	<#if column.displays??>
		<#list column.displays as key, display>
			<#if key=="form">
				<#switch display.element.class.simpleName>
					<#case 'Select'>
		//$('.select2').select2();
						<#break>
					<#case 'DateMask'>
		$('${'#'}${lower_camel('obj_'+column.name)}').inputmask({
			alias: 'yyyy-mm-dd',
			placeholder: 'yyyy-mm-dd',
			oncomplete: function(e){
				self.$set(self.item, '${lower_underscore(column.name)}', $(this).val());
			}
		});
						<#break>
					<#case 'DatePicker'>
		$('${'#'}${lower_camel('obj_'+column.name)}').datepicker({
			format: 'yyyy-mm-dd',
			autoclose: true
		});
		$('${'#'}${lower_camel('obj_'+column.name)}').on('changeDate', function(e){
			self.$set(self.item, '${lower_underscore(column.name)}', $(this).val());
		})	
						<#break>
					<#case 'DatetimePicker'>
		$('${'#'}${lower_camel('obj_'+column.name)}').datepicker({
			format: 'yyyy-mm-dd',
			locale: moment.locale('zh-cn')
		});
		$('${'#'}${lower_camel('obj_'+column.name)}').on('dp.change', function(e){
			self.$set(self.item, '${lower_underscore(column.name)}', $(this).val());
		})	
						<#break>
				</#switch>
			</#if>
		</#list>
	</#if>
</#list>
	}
});
app.load();
</script>