<#include "./func.ftl">
<!-- Generated by ${author} on ${now?string("yyyy-MM-dd HH:mm:ss")} -->
<div id="app">
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title">${table.remarks}列表</h3>
			<div class="box-tools">
				<quick-search @search="quickSearch"></quick-search>
			</div>
		</div>
		<div class="box-body">
			<table class="table table-condensed">
				<thead>
					<tr>
	<#list table.columns as column>
		<#if column.displays?? && column.displays?size gt 0>
			<#list column.displays as key, display>
				<#if key=='list'>
						<th<#list display.attributes as n, v> ${n}="${v}"</#list>>${to_label(column.remarks)}</th>
					<#break>
				</#if>
			</#list>
		</#if>
	</#list>
					</tr>
				</thead>
				<tbody>
					<tr v-for="(item, index) in items">
<#list table.columns as column>
	<#if column.displays?? && column.displays?size gt 0>
		<#list column.displays as key, display>
			<#if key=='list'>
						<td>
					<#if column.primaryKey>
							<input type="radio" name="id" :value="item.${lower_underscore(column.name)}" @change="select(index)" :checked="index==selectedRowIndex"/>
					<#else>
						<#if display.element??>
							<#switch display.element.class.simpleName>
								<#case 'Link'>
							<a :href="'#${lower_underscore(table.name)}.html?id='+item.id">{{ item.${lower_underscore(column.name)} }}</a>
									<#break>
							</#switch>
						<#else>
							<#if column.dictionary??>
							{{ item.${lower_underscore(column.name)} | ${lower_camel(column.name)}Filter }}
							<#else>
							{{ item.${lower_underscore(column.name)} }}
							</#if>						
						</#if>
					</#if>
						</td>
			</#if>
		</#list>
	</#if>
</#list>
					</tr>
				</tbody>		
			</table>
		</div>
		<div class="box-footer text-center">
			<div>
				<pagination :pagination="pagination" @pagechanged="goto"></pagination>
			</div>
			<button @click.prevent="add" class="btn btn-default">新增</button>
			<button @click.prevent="edit" class="btn btn-default">修改</button>
			<button @click.prevent="remove" class="btn btn-default">删除</button>
		</div>
	</div>


<#assign advancedSearch=false>
<#list table.columns as column>
	<#if column.displays?? && column.displays?size gt 0>
		<#list column.displays as key, display>
			<#if key=="advancedSearch">
				<#assign advancedSearch=true>
				<#assign header>
<form method="GET">    
<div class="modal fade" id="advancedSearchModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">			
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">高级检索</h4>
			</div>
			<div class="modal-body">				
				</#assign>
				<#assign content>
					<#if content??>${content}</#if>
				<div class="form-group">		
					<label for="${lower_camel('obj_'+column.name)}">
						${to_label(column.remarks)}
					</label>
					<#switch column.type>
						<#case 4>
						<#case 5>
						<#case -5>
						<#case -6>
					<select id="${lower_camel('obj_'+column.name)}" v-model="filters.${lower_underscore(column.name)}" name="${lower_underscore(column.name)}" class="form-control">
					<#if column.dictionary??>
						<option value="0">-</option>
						<#list column.dictionary as key, value>
						<option value="${key}">${value}</option>
						</#list>
					</#if>					
					</select>
							<#break>
						<#case 91>
					<input id="${lower_camel('obj_'+column.name)}" v-model="filters.${lower_underscore(column.name)}" name="${lower_underscore(column.name)}" class="form-control"/>
							<#break>
						<#default>
					<input id="${lower_camel('obj_'+column.name)}" type="text" v-model="filters.${lower_underscore(column.name)}" name="${lower_underscore(column.name)}" class="form-control"/>
					</#switch>
				</div>
				</#assign>
				<#assign footer>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
				<button type="button" @click.prevent="search" class="btn btn-primary">查询</button>
			</div>
		</div>
	</div>	
</div>
</form>
				</#assign>
			</#if>
		</#list>
	</#if>
</#list>
<#if advancedSearch>
<!-- Advanced Search Modal -->
<!-- Header -->
${header}
${content}
<!-- Footer -->
${footer}
<#else>
<!-- Advanced Search does NOT support -->
</#if>
</div>


<script>
/***
* Generated by CodeGenerator on ${now?string("yyyy-MM-dd HH:mm:ss")}
***/
app = new Vue({
	el: '#app',
	data: {
		selectedRowIndex: 0,
		items: {},
		pagination: {
			page: 1,
			page_count: 1,
			page_size: 10
		},
		filters: {}
	},
	filters: {
<#assign flag=false>	
<#list table.columns as column>
	<#if column.dictionary??>
		<#if flag>, </#if>
		${lower_camel(column.name)}Filter: function(i){
			return {
			<#list column.dictionary as key, value>
				${key}: "${value}"<#sep>, </#sep>
			</#list>
			}[i];
		}
		<#assign flag=true/>
	</#if>
</#list>
	},
	components: {
		pagination: Pagination,
		quickSearch: QuickSearch	
	},
	methods: {
		load: function(){
<#assign flag=false>
<#list table.columns as column>
	<#if column.dictionary??>
			<#if false>
				<#assign flag=true/>
			this.$http.get('${column.display.mapping.dataSource}').then(response => {
				Vue.filter('${lower_camel(column.name)}Filter', function(i){
					return data[i];
				});
			}).done(function(data){
			</#if>
	</#if>
</#list>
			this.refresh();
<#if flag>
			});
</#if>
		},
		refresh: function(){
		/*
			let promise = Promise.all([
				this.$http.get('./data/tags')
			]).then(responses => {
				//console.log('responses:', responses.length);
				{
					let tags = responses[0].data.tags;
					let items = tags.items;
					const TAGS = {};
					for(let item of items){
						TAGS[item.id] = item;
					}
					Vue.filter('tagIdFilter', function(i){
						if(i in TAGS){
							return TAGS[i].name;	
						}
						else{
							return i+"*";
						}
					});
				}*/
				let url = './data/${lower_underscore(pluralize(table.name))}';
				let params = [];
				//console.log('filters(search):', this.$data.filters);		
				for(let key in this.filters){
					let value = this.filters[key];
					if(value!=null && !StringUtils.isEmpty(value)){
						params.push(key+'='+encodeURI(value));
					}
				}
				if(this.pagination.page!=1){
					params.push('page='+this.pagination.page);
				}
				if(params.length!=0){
					url = url + '?' + params.join('&');
				}
				//console.log(url);
				this.$http.get(url).then(response => {
					let d = response.data;
					let paginatedList = d.${lower_underscore(pluralize(table.name))};
					//console.log('looooooooooooooaded.', response.data);
					this.$set(this, 'items', paginatedList.items);
					this.$set(this, 'pagination', paginatedList.pagination);
				});
				/*
			});*/
		},
		select: function(index){
			//console.log('selected:', index);
			this.$set(this, 'selectedRowIndex', index);
		},
		goto: function(page){
			console.log('Goto page: ', page);
			this.pagination.page = page;
			this.refresh();
		},
		quickSearch: function(keywords){
			console.log('Search on keywords: ', keywords);
			this.$set(this.$data.filters, 'nameLikes', keywords);
			this.search();
		},
		search: function(){
			console.log('Searching...');
			this.$set(this.pagination, 'page', 1);
			this.refresh();
		},
		add: function(){
			//console.log('add');
			router.redirect("#${lower_underscore(table.name+'_form')}.html");
		},
		edit: function(){
			let index = this.selectedRowIndex;
			let id = this.items[index].id;
			console.log('edit', id);
			router.goto('#${lower_underscore(table.name+'_form')}.html?id='+id);
		},
		remove: function(){
			let index = this.selectedRowIndex;
			let item = this.items[index];
			let id = item.id;
			let msg = '确定要删除"'+item.name+'"?';
			if(id && window.confirm(msg)){
				this.$http.delete('./data/${lower_underscore(table.name)}/'+id).then(response => {
					this.refresh();
				});
			}
		}
	}
});
app.load();
</script>