<!-- Generated by ${author} on ${now?string("yyyy-MM-dd HH:mm:ss")} -->
<div id="app">
	<div class="box">
	<#assign object_id=to_object_id(table.name,'tbl', '_'+random?string('000000'))>
	<div class="box-header with-border">
		<h3 class="box-title">${table.remarks}列表</h3>
		<div class="box-tools">
			<quick-search @search="quickSearch"></quick-search>
		</div>
	</div>
	<div class="box-body">
		<table class="table table-condensed">
			<thead>
				<tr>
	<#list table.columns as column>
		<#if column.display??>
			<th<#if column.display.width??> width="${column.display.width}"</#if><#if column.display.style??> class="${column.display.style}"</#if>>${column.remarks}</th>
		</#if>
	</#list>
				</tr>
			</thead>
			<tbody>
				<tr v-for="(item, index) in items">
<#list table.columns as column>
	<#assign flag=true>
	<#if column.display??>
		<#assign bind></#assign>
					<td<#if column.display.style??> class="${column.display.style}"</#if>>
					<#if column.primaryKey>
						<input type="radio" name="id" :value="item.${column.name}" @change="select(index)" :checked="index==selectedRowIndex"/>
					<#else>
						<#if column.display.element??>
							<#switch column.display.element.class.simpleName>
								<#case 'Link'>
						<a :href="'#case.html?id='+item.id">{{ item.${column.name} }}</a>
									<#break>
								<#default>
							</#switch>
						<#else>
							<#if column.display.mapping??>
						{{ item.${function_name(column.name, '', '')} | ${function_name(column.name, '', 'Filter')} }}
							<#else>
						{{ item.${function_name(column.name, '', '')} }}
							</#if>
						</#if>
					</#if>
					</td>
	</#if>
</#list>
				</tr>
			</tbody>		
		</table>
	</div>
	<div class="box-footer text-center">
		<div class="row">
		<div>
			<pagination :pagination="pagination" @pagechanged="goto"></pagination>
		</div>
		</div>
		<button @click.prevent="add" class="btn btn-default">新增</button>
		<button @click.prevent="edit" class="btn btn-default">修改</button>
		<button @click.prevent="remove" class="btn btn-default">删除</button>
	</div>
</div>

<!-- AdvancedSearchModal -->
<div class="modal fade" id="advancedSearchModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">

<form method="GET" @submit.prevent="search">  
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">高级检索</h4>
      </div>
      <div class="modal-body">

		<div class="form-group">		
			<label for="objTitle">
				名称
			</label>
			<textarea id="objTitle" v-model="searchConditions.nameLikes" name="title" cols="64" rows="4" class="form-control"></textarea>
		</div>
		<div class="form-group">		
			<label for="objType">
				类型*
			</label>
			<select id="objType" v-model="searchConditions.type" name="type" class="form-control">
				<option value="1">打架斗殴</option>
				<option value="2">盗窃</option>
				<option value="3">卖淫嫖娼</option>
			</select>
		</div>
		<div class="form-group">		
			<label for="objSource">
				来源*
			</label>
			<select id="objSource" v-model="searchConditions.source" name="source" class="form-control">
				<option value="1">110</option>
				<option value="2">自首</option>
			</select>
		</div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="submit" @click="search" class="btn btn-primary">查询</button>
      </div>
    </div>

</form>    
  </div>
</div>

</div>

<script id="tplQuickSearch" type="text/template">
	<form method="GET" @submit.prevent="search" class="form-inline">
	<div class="box-tools">
		<div class="input-group input-group-sm">
			<input v-model="keywords" type="text" name="keywords" class="form-control pull-right" placeholder="Search">
			<div class="input-group-btn">
				<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
			</div>
		</div>
		<a v-if="showAdvanced" href="#" class="btn-link btn-sm" data-toggle="modal" data-target="#advancedSearchModel">高级搜索</a>
	</div>
	</form>
</script>


<script id="tplPagination" type="text/template">
  <ul class="pagination pagination-sm no-margin">
    <li>
      <a v-if="pagination.page!=1" @click.prevent="goto(1)"  href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
	  <span v-else aria-hidden="true">&laquo;</span>
    </li>
    <li v-for="i in pageNumbers">
    	<a v-if="i!=pagination.page" @click.prevent="goto(i)" href="#">{{ i }}</a>
    	<span v-else>{{ i }}</span>
    </li>
    <li>
      <a v-if="pagination.page!=pagination.totalPages" @click.prevent="goto(pagination.totalPages)" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
	  <span v-else aria-hidden="true">&raquo;</span>
    </li>
  </ul>
</script>

<script>
/***
* Generated by CodeGenerator on ${now?string("yyyy-MM-dd HH:mm:ss")}
***/
app = new Vue({
	el: '#app',
	data: {
		selectedRowIndex: 0,
		items: [],
		pagination: {
			page: 1,
			totalPages: 10,
			pageSize: 10
		},
		searchConditions: {
			nameLikes: "",
			type: 1,
			source: 1
		}
	},
	filters: {
<#assign flag=false>	
<#list table.columns as column>
	<#if column.display??>
		<#if column.display.mapping??>
			<#if column.display.mapping.options??>
				<#if flag>, </#if>
		<#assign flag=true/>
		${function_name(column.name, '', 'Filter')}: function(i){
			return {
			<#list column.display.mapping.options as option>
				"${option.value}": "${option.name}"<#sep>, </#sep>
			</#list>
			}[i];
		}
			</#if>
		</#if>
	</#if>
</#list>
	},
	components: {
		pagination: {
			template: '#tplPagination',
			props: ['pagination'],
			methods: {
				goto: function(i){
					this.$emit('pagechanged', i);
					//this.$parent.pagination.page = i;
				}
			},
			computed:{
				pageNumbers: function(){
					let totalPages = this.pagination.totalPages;
					let page = this.pagination.page;
					let from, to, len = 9;
					if(totalPages>len){
						from = page-Math.floor((len-1)/2);
						to = page+Math.floor((len-1)/2);
						if(from<1){
							from = 1;
							to = from+(len-1);
						}
						if(to>totalPages){
							to = totalPages;
							from = to-(len-1);
						}
					}
					else{
						from = 1;
						to = totalPages;
					}
					let pageNumbers = [];
					for(let i=from; i<=to; i++){
						pageNumbers.push(i);
					}
					return pageNumbers;
				}
			}
		},
		quickSearch: {
			template: '#tplQuickSearch',
			data: function(){
				return {
					keywords: "",
					showAdvanced: true
				}
			},
			methods: {
				search: function(){
					if(!StringUtils.isEmpty(this.keywords)){
						this.$emit('search', this.keywords);
					}
				}
			}
		}		
	},
	methods: {
		load: function(){
			let _this = this;
<#assign flag=false>
<#list table.columns as column>
	<#if column.display??>
		<#if column.display.mapping??>
			<#if column.display.mapping.dataSource??>
				<#assign flag=true/>
			$.get('${column.display.mapping.dataSource}', function(data){
				Vue.filter('${function_name(column.name, '', 'Filter')}', function(i){
					return data[i];
				});
			}).done(function(data){
			</#if>
		</#if>
	</#if>
</#list>
				_this.refresh();
<#if flag>
			});
</#if>
		},
		refresh: function(){
			console.log(this.searchConditions);
			let url = './json/${table.name}_list.json';
			let params = [];
			for(let key in this.searchConditions){
				params.push(key+'='+encodeURI(this.searchConditions[key]));
			}
			if(this.pagination.page!=1){
				params.push('page='+this.pagination.page);
			}
			if(params.length!=0){
				url = url + '?' + params.join('&');
			}
			console.log(url);
			let _this = this;
			$.ajax({
				url: url,
				type: 'GET'
			}).done(function(d){
				console.log('looooooooooooooaded.');
				_this.items = d.data;
				_this.pagination.totalPages = d.pagination.totalPages;
			});
		},
		select: function(index){
			console.log('selected:', index);
			this.selectedRowIndex = index;
		},
		goto: function(page){
			console.log('Goto page: ', page);
			this.pagination.page = page;
			this.refresh();
		},
		quickSearch: function(keywords){
			console.log('Search on keywords: ', keywords);
			this.searchConditions.nameLikes = keywords;
			this.search();
		},
		search: function(){
			console.log('Searching...');
			this.pagination.page = 1;
			this.refresh();			
		},
		<#assign add_url>#${table.name}_form.html</#assign>
		add: function(){
			console.log('add');
			location.href = "${add_url}";
		},
		<#assign edit_url>#${table.name}_form.html</#assign>
		edit: function(){
			let index = this.selectedRowIndex;
			let id = this.items[index].id;
			console.log('edit', id);
			location.href = '${edit_url}?id='+encodeURI(id);
		},
		<#assign remove_url>./${table.name}.do</#assign>
		remove: function(){
			let _this = this;
			let index = this.selectedRowIndex;
			let item = this.items[index];
			let id = item.id;
			let msg = '确定要删除"'+item.title+'"?';
			if(window.confirm(msg)){
				$.ajax({
					url:'${remove_url}?id='+encodeURI(id),
					type: 'DELETE',
					data: JSON.stringify({"id": id})
				}).done(function(data){
					_this.items.splice(_this.selectedRowIndex, 1);
					_this.load();
				});
			}
		}
	}
});
app.load();
</script>
<#function to_object_id str prefix postfix>
	<#local name=prefix>
	<#list str?split("_") as word>
		<#local name=name+word?capitalize>
	</#list>
	<#local name=name+postfix>
	<#return name>
</#function>

<#function function_name str prefix postfix>
	<#local name=prefix>
	<#list str?split("_") as word>
		<#if word_index==0>
			<#local name=name+word>
		<#else>
			<#local name=name+word?capitalize>
		</#if>
	</#list>
	<#local name=name+postfix>
	<#return name>
</#function>